export const languageMap = {
  en: "English",
  fr: "French",
  es: "Spanish",
  sw: "Swahili",
  ar: "Arabic",
  hi: "Hindi",
  bn: "Bengali",
  id: "Indonesian",
  jv: "Javanese",
  ms: "Malay",
  pt: "Portuguese",
  ru: "Russian",
  vi: "Vietnamese",
  zh: "Chinese",
  ha: "Hausa",
  yo: "Yoruba",
  am: "Amharic",
  rw: "Kinyarwanda",
  kg: "Kongo",
  ln: "Lingala",
  wo: "Wolof",
  ig: "Igbo",
  zu: "Zulu",
  kk: "Kazakh",
  uz: "Uzbek",
  km: "Khmer",
  lo: "Lao",
  my: "Burmese",
  ne: "Nepali",
  si: "Sinhala",
  ta: "Tamil",
  te: "Telugu",
  th: "Thai",
  tl: "Tagalog",
  ur: "Urdu",
  prs: "Persian",
  sn: "Shona",
  ny: "Chichewa",
  st: "Sesotho",
  xh: "Xhosa",
  ss: "Swazi",
  tn: "Tswana",
  ts: "Tsonga",
  ve: "Venda",
  nr: "South Ndebele",
  nn: "Northern Ndebele",
  nso: "Northern Sotho",
  kl: "Kalaallisut",
  bem: "Bemba",
  umb: "Umbundu",
  kmb: "Kimbundu",
  luo: "Luo",
  ksb: "Shambala",
  mfe: "Morisyen",
  ff: "Fula",
  ewo: "Ewondo",
  fon: "Fon",
  ibo: "Igbo",
  kin: "Kinyarwanda",
  sna: "Shona",
  toi: "Tonga (Zambia)",
  tsn: "Tswana",
  tso: "Tsonga",
  ven: "Venda",
  yor: "Yoruba",
};

export const IloveWater = {
  en: "I love water",
  fr: "J'aime l'eau",
  es: "Me encanta el agua",
  sw: "Ninapenda maji",
  ar: "أنا أحب الماء",
  hi: "मुझे पानी पसंद है",
  bn: "আমি পানি ভালোবাসি",
  id: "Saya suka air",
  jv: "Aku seneng banyu",
  ms: "Saya suka air",
  pt: "Eu amo água",
  ru: "Я люблю воду",
  vi: "Tôi yêu nước",
  zh: "我爱水",
  ha: "Ina son ruwa",
  yo: "Mo fẹ́ràn omi",
  am: "ውሃ እወዳለሁ",
  rw: "Ndakunda amazi",
  kg: "Nalingi mai",
  ln: "Nalingaka mai",
  wo: "Dama nanu ndox",
  ig: "Ahụrụ m mmiri n'anya",
  zu: "Ngiyathanda amanzi",
  kk: "Мен суды жақсы көремін",
  uz: "Men suvni yaxshi ko'raman",
  km: "ខ្ញុំស្រលាញ់ទឹក",
  lo: "ຂ້ອຍຮັກນ້ຳ",
  my: "ကျွန်မ ရေကိုချစ်တယ်",
  ne: "म पानी मन पराउँछु",
  si: "මම වතුරට ආදරෙයි",
  ta: "எனக்கு தண்ணீர் பிடிக்கும்",
  te: "నేను నీటిని ప్రేమిస్తున్నాను",
  th: "ฉันรักน้ำ",
  tl: "Mahal ko ang tubig",
  ur: "مجھے پانی سے محبت ہے",
  prs: "من آب را دوست دارم",
  sn: "Ndinoda mvura",
  ny: "Ndimakonda madzi",
  st: "Ke rata metsi",
  xh: "Ndiyalithanda amanzi",
  ss: "Ngiyawutsandza emanti",
  tn: "Ke rata metsi",
  ts: "Ndzi rhandza mati",
  ve: "Ndi funa maḓi",
  nr: "Ngithanda amanzi",
  nn: "Mi randza mati",
  nso: "Ke rata meetse",
  kl: "Ek is lief vir water",
  bem: "Nalitemwa amenshi",
  umb: "Ngweti oholo okuwa",
  kmb: "Nalingi maza",
  luo: "Ahero pi",
  ksb: "Nakipenda machi",
  mfe: "Mo kontan dilo",
  ff: "Mi yiɗi ndiyam",
  ewo: "Ma wɔ̌ŋlɛ mǎnjě",
  fon: "Un yiwlɛ sin",
  ibo: "Ahụrụ m mmiri n'anya",
  kin: "Ndakunda amazi",
  sna: "Ndinoda mvura",
  toi: "Ke rata metsi",
  tsn: "Ke rata metsi",
  tso: "Ndzi rhandza mati",
  ven: "Ndi funa maḓi",
  yor: "Mo fẹ́ràn omi",
};
